package Views;

import Services.IDongSanPhamService;
import Services.IMauSacService;
import Services.INhaSanXuatService;
import Services.ISanPhamService;
import Services.Impl.DongSanPhamServiceImpl;
import Services.Impl.MauSacServiceImpl;
import Services.Impl.NhaSanXuatServiceImpl;
import Services.Impl.SanPhamServiceImpl;
import ViewModels.QLDongSanPham;
import ViewModels.QLMauSac;
import ViewModels.QLNhaSanXuat;
import ViewModels.QLSanPham;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cvdoa
 */
public class ThongTinSPFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrangChuFrame
     */
    private DefaultTableModel tableModel = new DefaultTableModel();
    private ISanPhamService sanPhamService = new SanPhamServiceImpl();
    private INhaSanXuatService nhaSanXuatService = new NhaSanXuatServiceImpl();
    private IMauSacService mauSacService = new MauSacServiceImpl();
    private IDongSanPhamService dongSanPhamService = new DongSanPhamServiceImpl();
    int next = 0;
    
    public ThongTinSPFrame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        loadSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadSanPham() {
        tableModel = (DefaultTableModel) tb_DanhSach.getModel();
        tableModel.setRowCount(0);
        for (QLSanPham sp : sanPhamService.getListSanPham()) {
            tableModel.addRow(sp.toDataRow());
        }
    }
    
    public void loadNSX() {
        tableModel = (DefaultTableModel) tb_DanhSach.getModel();
        tableModel.setRowCount(0);
        for (QLNhaSanXuat nsx : nhaSanXuatService.getListNSX()) {
            tableModel.addRow(nsx.toDataRow());
        }
    }
    
    public void loadMauSac() {
        tableModel = (DefaultTableModel) tb_DanhSach.getModel();
        tableModel.setRowCount(0);
        for (QLMauSac ms : mauSacService.getListMauSac()) {
            tableModel.addRow(ms.toDataRow());
        }
    }
    
    public void loadDongSP() {
        tableModel = (DefaultTableModel) tb_DanhSach.getModel();
        tableModel.setRowCount(0);
        for (QLDongSanPham dsp : dongSanPhamService.getListDongSanPham()) {
            tableModel.addRow(dsp.toDataRow());
        }
    }
    
    public void clearFrom() {
        tb_DanhSach.setRowSelectionAllowed(false);
        txt_Ma.setEditable(true);
        lbl_id.setText("-");
        txt_Ma.setText("");
        txt_Ten.setText("");
    }
    
    public void loadData() {
        if (next == 0) {
            loadSanPham();
        } else if (next == 1) {
            loadNSX();
        } else if (next == 2) {
            loadMauSac();
        } else if (next == 3) {
            loadDongSP();
        }
    }
    
    public boolean check0() {
        if (txt_Ma.getText().trim().isEmpty() || txt_Ten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            return false;
        }
        if (sanPhamService.getOne(txt_Ma.getText()) == null) {
        } else {
            JOptionPane.showMessageDialog(this, "Trùng mã không thể thêm");
            return false;
        }
        return true;
    }
    
    public boolean check1() {
        if (txt_Ma.getText().trim().isEmpty() || txt_Ten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            return false;
        }
        if (nhaSanXuatService.getOne(txt_Ma.getText()) == null) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Trùng mã không thể thêm");
            return false;
        }
        return true;
    }
    
    public boolean check2() {
        if (txt_Ma.getText().trim().isEmpty() || txt_Ten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            return false;
        }
        if (mauSacService.getOne(txt_Ma.getText()) == null) {
        } else {
            JOptionPane.showMessageDialog(this, "Trùng mã không thể thêm");
            return false;
        }
        return true;
    }
    
    public boolean check3() {
        if (txt_Ma.getText().trim().isEmpty() || txt_Ten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            return false;
        }
        if (dongSanPhamService.getOne(txt_Ma.getText()) == null) {
        } else {
            JOptionPane.showMessageDialog(this, "Trùng mã không thể thêm");
            return false;
        }
        
        return true;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_Ma = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DanhSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        cb_Display = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_Tile = new javax.swing.JLabel();

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(650, 798));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Mã :");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Tên :");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("id :");

        lbl_id.setText("_");

        tb_DanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Mã", "Tên"
            }
        ));
        tb_DanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DanhSach);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manager_Add.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manager_Up.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setMaximumSize(new java.awt.Dimension(80, 30));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_Delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manager_Delete.png"))); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manager_Clear.png"))); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Delete)
                .addGap(18, 18, 18)
                .addComponent(btn_Clear)
                .addContainerGap())
        );

        cb_Display.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_Display.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sản Phẩm", "Nhà Sản Xuất", "Màu Sắc", "Dòng Sản Phẩm" }));
        cb_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DisplayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Đang Hiển Thị thông Tin");

        lbl_Tile.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        lbl_Tile.setForeground(new java.awt.Color(153, 0, 153));
        lbl_Tile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tile.setText("Sản Phẩm");
        lbl_Tile.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 152, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addComponent(lbl_Tile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lbl_Tile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(lbl_id))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(59, 59, 59))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DisplayActionPerformed
        // TODO add your handling code here:
        String tile = cb_Display.getSelectedItem().toString();
        lbl_Tile.setText(tile);
        if (cb_Display.getSelectedItem().equals("Sản Phẩm")) {
            next = 0;
        } else if (cb_Display.getSelectedItem().equals("Nhà Sản Xuất")) {
            next = 1;
        } else if (cb_Display.getSelectedItem().equals("Màu Sắc")) {
            next = 2;
        } else if (cb_Display.getSelectedItem().equals("Dòng Sản Phẩm")) {
            next = 3;
        }
        loadData();
    }//GEN-LAST:event_cb_DisplayActionPerformed

    private void tb_DanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhSachMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhSach.getSelectedRow();
        tb_DanhSach.setRowSelectionAllowed(true);
        txt_Ma.setEditable(false);
        lbl_id.setText(tb_DanhSach.getValueAt(row, 0).toString());
        txt_Ma.setText(tb_DanhSach.getValueAt(row, 1).toString());
        txt_Ten.setText(tb_DanhSach.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tb_DanhSachMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn update không ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (next == 0) {
                QLSanPham qlsp = new QLSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = sanPhamService.update(lbl_id.getText(), qlsp);
                loadSanPham();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 1) {
                QLNhaSanXuat qlnsx = new QLNhaSanXuat(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = nhaSanXuatService.update(lbl_id.getText(), qlnsx);
                loadNSX();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 2) {
                QLMauSac qlms = new QLMauSac(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = mauSacService.update(lbl_id.getText(), qlms);
                loadMauSac();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 3) {
                QLDongSanPham qldsp = new QLDongSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = dongSanPhamService.update(lbl_id.getText(), qldsp);
                loadDongSP();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn từ chối update");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn delete không ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (next == 0) {
                QLSanPham qlsp = new QLSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = sanPhamService.delete(lbl_id.getText());
                loadSanPham();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 1) {
                QLNhaSanXuat qlnsx = new QLNhaSanXuat(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = nhaSanXuatService.delete(lbl_id.getText());
                loadNSX();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 2) {
                QLMauSac qlms = new QLMauSac(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = mauSacService.delete(lbl_id.getText());
                loadMauSac();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            } else if (next == 3) {
                QLDongSanPham qldsp = new QLDongSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = dongSanPhamService.delete(lbl_id.getText());
                loadDongSP();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn từ chối delete");
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        clearFrom();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (next == 0) {
            if (check0()) {
                QLSanPham qlsp = new QLSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = sanPhamService.insert(qlsp);
                loadSanPham();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        } else if (next == 1) {
            if (check1()) {
                QLNhaSanXuat qlnsx = new QLNhaSanXuat(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = nhaSanXuatService.insert(qlnsx);
                loadNSX();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        } else if (next == 2) {
            if (check2()) {
                
                QLMauSac qlms = new QLMauSac(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = mauSacService.insert(qlms);
                loadMauSac();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        } else if (next == 3) {
            if (check3()) {
                QLDongSanPham qldsp = new QLDongSanPham(lbl_id.getText(), txt_Ma.getText(), txt_Ten.getText());
                String mess = dongSanPhamService.insert(qldsp);
                loadDongSP();
                JOptionPane.showMessageDialog(this, mess);
                clearFrom();
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_Display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Tile;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tb_DanhSach;
    private javax.swing.JTextField txt_Ma;
    private javax.swing.JTextField txt_Ten;
    // End of variables declaration//GEN-END:variables
}
